spring:
  application:
    name: kaiapi-order
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kaiapi
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis 配置
  redis:
    port: 6379
    host: 192.168.4.134
    database: 0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  rabbitmq:
    addresses: 192.168.4.134
    port: 5672
    virtual-host: /
    username: admin
    password: admin
    publisher-confirm-type: correlated #开启发送端确认
    publisher-returns: true #开启发送端消息抵达队列的确认
    template:
      mandatory: true #只要抵达队列，以异步发送优先回调我们这个returnsConfirm
    listener:
      simple:
        acknowledge-mode: manual #手动确认接收到的消息
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息
server:
  port: 8083
  servlet:
    context-path: /order
    session:
      cookie:
        same-site: none
        secure: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

dubbo:
  application:
    name: kaiapi-order-consumer
    qos:
      port: 33333
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
